"""empty message

Revision ID: 1f47d352e7a1
Revises: 1d939f9cd56a
Create Date: 2021-08-25 23:04:23.693498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f47d352e7a1'
down_revision = '1d939f9cd56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=1024), nullable=True))
    op.add_column('user', sa.Column('position', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('office', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salary')
    op.drop_column('user', 'office')
    op.drop_column('user', 'position')
    op.drop_column('user', 'password')
    op.drop_column('user', 'update_time')
    op.drop_column('user', 'create_time')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
