"""empty message

Revision ID: 29f09cf246d5
Revises: 55d8a44fdf02
Create Date: 2021-09-19 23:01:07.954761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f09cf246d5'
down_revision = '55d8a44fdf02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_table_define',
    sa.Column('class_name', sa.String(length=2), nullable=False),
    sa.Column('tbl_code', sa.String(length=20), nullable=False),
    sa.Column('tbl_name', sa.String(length=20), nullable=True),
    sa.Column('field_code', sa.String(length=20), nullable=True),
    sa.Column('field_name', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('decimal', sa.Integer(), nullable=True),
    sa.Column('nullable', sa.String(length=1), nullable=True),
    sa.Column('doc', sa.String(length=256), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('class_name', 'tbl_code')
    )
    op.add_column('m_system_code', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('m_system_code', 'code_kbn',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('m_system_code', 'code_no',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_system_code', 'code_no',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('m_system_code', 'code_kbn',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.drop_column('m_system_code', 'id')
    op.drop_table('m_table_define')
    # ### end Alembic commands ###
