"""update.

Revision ID: 361832984684
Revises: c99a5775bb9c
Create Date: 2021-09-19 10:28:34.533416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '361832984684'
down_revision = 'c99a5775bb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_user_info',
    sa.Column('abort_div', sa.Integer(), nullable=True),
    sa.Column('update_user_id', sa.String(length=32), nullable=True),
    sa.Column('update_count', sa.Integer(), nullable=True),
    sa.Column('update_pgid', sa.String(length=512), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('telephone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('Address1', sa.String(length=256), nullable=True),
    sa.Column('Address2', sa.String(length=256), nullable=True),
    sa.Column('photo', sa.String(length=1024), nullable=True),
    sa.Column('factory_cd', sa.String(length=2), nullable=True),
    sa.Column('user_cd', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['factory_cd'], ['m_factory.factory_cd'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_cd'], ['m_user.user_cd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_user_info_abort_div'), 'm_user_info', ['abort_div'], unique=False)
    op.create_index(op.f('ix_m_user_info_factory_cd'), 'm_user_info', ['factory_cd'], unique=False)
    op.create_index(op.f('ix_m_user_info_id'), 'm_user_info', ['id'], unique=False)
    op.create_index(op.f('ix_m_user_info_sex'), 'm_user_info', ['sex'], unique=False)
    op.create_index(op.f('ix_m_user_info_user_cd'), 'm_user_info', ['user_cd'], unique=False)
    op.drop_index('ix_m_calendar_abort_div', table_name='m_calendar')
    op.drop_index('ix_m_calendar_event_cd', table_name='m_calendar')
    op.drop_index('ix_m_calendar_factory_cd', table_name='m_calendar')
    op.drop_index('ix_m_calendar_holiday_flg', table_name='m_calendar')
    op.drop_table('m_calendar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_calendar',
    sa.Column('abort_div', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_user_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('update_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_pgid', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('calendar_date', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('Seq_No', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('holiday_flg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('holiday_nm', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('event_cd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_nm', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('event_time1', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('event_time2', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('month_end_flg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('sche_flg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('factory_cd', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['factory_cd'], ['m_factory.factory_cd'], name='m_calendar_factory_cd_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calendar_date', 'Seq_No', name='m_calendar_pkey')
    )
    op.create_index('ix_m_calendar_holiday_flg', 'm_calendar', ['holiday_flg'], unique=False)
    op.create_index('ix_m_calendar_factory_cd', 'm_calendar', ['factory_cd'], unique=False)
    op.create_index('ix_m_calendar_event_cd', 'm_calendar', ['event_cd'], unique=False)
    op.create_index('ix_m_calendar_abort_div', 'm_calendar', ['abort_div'], unique=False)
    op.drop_index(op.f('ix_m_user_info_user_cd'), table_name='m_user_info')
    op.drop_index(op.f('ix_m_user_info_sex'), table_name='m_user_info')
    op.drop_index(op.f('ix_m_user_info_id'), table_name='m_user_info')
    op.drop_index(op.f('ix_m_user_info_factory_cd'), table_name='m_user_info')
    op.drop_index(op.f('ix_m_user_info_abort_div'), table_name='m_user_info')
    op.drop_table('m_user_info')
    # ### end Alembic commands ###
