"""empty message

Revision ID: 66b29a15bd91
Revises: 7ff943328b36
Create Date: 2021-09-21 20:02:50.857963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b29a15bd91'
down_revision = '7ff943328b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_user_info', sa.Column('address1', sa.String(length=256), nullable=True))
    op.add_column('m_user_info', sa.Column('address2', sa.String(length=256), nullable=True))
    op.drop_column('m_user_info', 'Address2')
    op.drop_column('m_user_info', 'Address1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_user_info', sa.Column('Address1', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('m_user_info', sa.Column('Address2', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('m_user_info', 'address2')
    op.drop_column('m_user_info', 'address1')
    # ### end Alembic commands ###
