"""empty message

Revision ID: 6aac56771d9c
Revises: 0e12ed527e45
Create Date: 2021-08-26 13:52:14.920477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aac56771d9c'
down_revision = '0e12ed527e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_department_id'), 'tb_department', ['id'], unique=False)
    op.create_table('tb_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_menu_id'), 'tb_menu', ['id'], unique=False)
    op.add_column('tb_users', sa.Column('status', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'status')
    op.drop_index(op.f('ix_tb_menu_id'), table_name='tb_menu')
    op.drop_table('tb_menu')
    op.drop_index(op.f('ix_tb_department_id'), table_name='tb_department')
    op.drop_table('tb_department')
    # ### end Alembic commands ###
