"""empty message

Revision ID: 6eb737cc2c43
Revises: 6aac56771d9c
Create Date: 2021-08-26 14:19:59.204241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb737cc2c43'
down_revision = '6aac56771d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tb_users_department_id'), 'tb_users', ['department_id'], unique=False)
    op.create_foreign_key(None, 'tb_users', 'tb_department', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_users', type_='foreignkey')
    op.drop_index(op.f('ix_tb_users_department_id'), table_name='tb_users')
    op.drop_column('tb_users', 'department_id')
    # ### end Alembic commands ###
