"""empty message

Revision ID: 76f4b17fec81
Revises: c07c2841cbed
Create Date: 2021-08-31 10:13:45.822308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f4b17fec81'
down_revision = 'c07c2841cbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'age')
    # ### end Alembic commands ###
