"""empty message

Revision ID: 7847365fcf82
Revises: 76f4b17fec81
Create Date: 2021-08-31 10:15:38.738975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7847365fcf82'
down_revision = '76f4b17fec81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'gender',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'gender',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###
