"""empty message

Revision ID: 7ff943328b36
Revises: d1fff18364f9
Create Date: 2021-09-21 19:46:08.488464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff943328b36'
down_revision = 'd1fff18364f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_user', sa.Column('update_user_id', sa.String(length=32), nullable=True))
    op.add_column('m_user', sa.Column('update_count', sa.Integer(), nullable=True))
    op.add_column('m_user', sa.Column('update_pgid', sa.String(length=512), nullable=True))
    op.add_column('m_user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('m_user', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('m_user', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_user', 'comment')
    op.drop_column('m_user', 'update_time')
    op.drop_column('m_user', 'create_time')
    op.drop_column('m_user', 'update_pgid')
    op.drop_column('m_user', 'update_count')
    op.drop_column('m_user', 'update_user_id')
    # ### end Alembic commands ###
