"""empty message

Revision ID: 85ee87746147
Revises: 7847365fcf82
Create Date: 2021-08-31 11:32:40.356616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ee87746147'
down_revision = '7847365fcf82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_menu', sa.Column('path', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_menu', 'path')
    # ### end Alembic commands ###
