"""empty message

Revision ID: 93bba9d1638a
Revises: 
Create Date: 2021-09-20 23:18:29.514384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bba9d1638a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_system_code',
    sa.Column('update_user_id', sa.String(length=32), nullable=True),
    sa.Column('update_count', sa.Integer(), nullable=True),
    sa.Column('update_pgid', sa.String(length=512), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_kbn', sa.String(length=3), nullable=True),
    sa.Column('code_kbn_nm', sa.String(length=32), nullable=True),
    sa.Column('code_no', sa.String(length=3), nullable=True),
    sa.Column('code_nm', sa.String(length=32), nullable=True),
    sa.Column('flug1', sa.String(length=1), nullable=True),
    sa.Column('flug1_nm', sa.String(length=32), nullable=True),
    sa.Column('flug2', sa.String(length=1), nullable=True),
    sa.Column('flug2_nm', sa.String(length=10), nullable=True),
    sa.Column('flug3', sa.String(length=1), nullable=True),
    sa.Column('flug3_nm', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_kbn', 'code_no', name='unique_kbn_no')
    )
    op.create_table('m_table_define',
    sa.Column('class_name', sa.String(length=2), nullable=False),
    sa.Column('tbl_code', sa.String(length=20), nullable=False),
    sa.Column('tbl_name', sa.String(length=20), nullable=True),
    sa.Column('field_code', sa.String(length=20), nullable=True),
    sa.Column('field_name', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('decimal', sa.Integer(), nullable=True),
    sa.Column('nullable', sa.String(length=1), nullable=True),
    sa.Column('doc', sa.String(length=256), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('class_name', 'tbl_code')
    )
    op.create_table('m_factory',
    sa.Column('update_user_id', sa.String(length=32), nullable=True),
    sa.Column('update_count', sa.Integer(), nullable=True),
    sa.Column('update_pgid', sa.String(length=512), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('factory_cd', sa.String(length=2), nullable=False),
    sa.Column('factory_nm', sa.String(length=64), nullable=True),
    sa.Column('abort_div', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abort_div'], ['m_system_code.id'], ),
    sa.PrimaryKeyConstraint('factory_cd')
    )
    op.create_table('m_department',
    sa.Column('update_user_id', sa.String(length=32), nullable=True),
    sa.Column('update_count', sa.Integer(), nullable=True),
    sa.Column('update_pgid', sa.String(length=512), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('dep_cd', sa.String(length=10), nullable=False),
    sa.Column('dep_name', sa.String(length=64), nullable=True),
    sa.Column('factory_cd', sa.String(length=2), nullable=True),
    sa.Column('abort_div', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abort_div'], ['m_system_code.id'], ),
    sa.ForeignKeyConstraint(['factory_cd'], ['m_factory.factory_cd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dep_cd')
    )
    op.create_index(op.f('ix_m_department_factory_cd'), 'm_department', ['factory_cd'], unique=False)
    op.create_table('m_user',
    sa.Column('user_cd', sa.String(length=6), nullable=False),
    sa.Column('user_nm', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.Column('create_user_id', sa.String(length=6), nullable=True),
    sa.Column('role_cd', sa.Integer(), nullable=True),
    sa.Column('duty_cd', sa.Integer(), nullable=True),
    sa.Column('dep_cd', sa.String(length=10), nullable=True),
    sa.Column('factory_cd', sa.String(length=2), nullable=True),
    sa.Column('abort_div', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abort_div'], ['m_system_code.id'], ),
    sa.ForeignKeyConstraint(['dep_cd'], ['m_department.dep_cd'], ),
    sa.ForeignKeyConstraint(['duty_cd'], ['m_system_code.id'], ),
    sa.ForeignKeyConstraint(['factory_cd'], ['m_factory.factory_cd'], ),
    sa.ForeignKeyConstraint(['role_cd'], ['m_system_code.id'], ),
    sa.PrimaryKeyConstraint('user_cd')
    )
    op.create_table('m_user_info',
    sa.Column('update_user_id', sa.String(length=32), nullable=True),
    sa.Column('update_count', sa.Integer(), nullable=True),
    sa.Column('update_pgid', sa.String(length=512), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('telephone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('Address1', sa.String(length=256), nullable=True),
    sa.Column('Address2', sa.String(length=256), nullable=True),
    sa.Column('photo', sa.String(length=1024), nullable=True),
    sa.Column('factory_cd', sa.String(length=2), nullable=True),
    sa.Column('user_cd', sa.String(length=6), nullable=True),
    sa.Column('abort_div', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abort_div'], ['m_system_code.id'], ),
    sa.ForeignKeyConstraint(['factory_cd'], ['m_factory.factory_cd'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_cd'], ['m_user.user_cd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_user_info_factory_cd'), 'm_user_info', ['factory_cd'], unique=False)
    op.create_index(op.f('ix_m_user_info_id'), 'm_user_info', ['id'], unique=False)
    op.create_index(op.f('ix_m_user_info_sex'), 'm_user_info', ['sex'], unique=False)
    op.create_index(op.f('ix_m_user_info_user_cd'), 'm_user_info', ['user_cd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m_user_info_user_cd'), table_name='m_user_info')
    op.drop_index(op.f('ix_m_user_info_sex'), table_name='m_user_info')
    op.drop_index(op.f('ix_m_user_info_id'), table_name='m_user_info')
    op.drop_index(op.f('ix_m_user_info_factory_cd'), table_name='m_user_info')
    op.drop_table('m_user_info')
    op.drop_table('m_user')
    op.drop_index(op.f('ix_m_department_factory_cd'), table_name='m_department')
    op.drop_table('m_department')
    op.drop_table('m_factory')
    op.drop_table('m_table_define')
    op.drop_table('m_system_code')
    # ### end Alembic commands ###
