"""empty message

Revision ID: 94d8068875be
Revises: 6eb737cc2c43
Create Date: 2021-08-28 22:42:03.686974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d8068875be'
down_revision = '6eb737cc2c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('gender', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'gender')
    # ### end Alembic commands ###
