"""empty message

Revision ID: 96edc2109d3c
Revises: e9c765697e7b
Create Date: 2021-09-26 23:58:32.468942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96edc2109d3c'
down_revision = 'e9c765697e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_system_code', sa.Column('factory_cd', sa.String(length=2), nullable=True))
    op.create_index(op.f('ix_m_system_code_factory_cd'), 'm_system_code', ['factory_cd'], unique=False)
    op.create_unique_constraint('unique_kbn_no', 'm_system_code', ['code_kbn', 'code_no', 'factory_cd'])
    op.create_foreign_key(None, 'm_system_code', 'm_factory', ['factory_cd'], ['factory_cd'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'm_system_code', type_='foreignkey')
    op.drop_constraint('unique_kbn_no', 'm_system_code', type_='unique')
    op.drop_index(op.f('ix_m_system_code_factory_cd'), table_name='m_system_code')
    op.drop_column('m_system_code', 'factory_cd')
    # ### end Alembic commands ###
