"""empty message

Revision ID: b26b9b539e09
Revises: b29030420b6f
Create Date: 2021-08-29 00:02:35.365797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26b9b539e09'
down_revision = 'b29030420b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('gender', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
