"""empty message

Revision ID: b29030420b6f
Revises: 94d8068875be
Create Date: 2021-08-28 23:58:44.526293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29030420b6f'
down_revision = '94d8068875be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'gender',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'gender',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
