"""empty message

Revision ID: d1fff18364f9
Revises: a6d7de9f15fb
Create Date: 2021-09-21 12:54:04.466140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fff18364f9'
down_revision = 'a6d7de9f15fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_kbn_no', 'm_system_code', type_='unique')
    op.create_unique_constraint('unique_kbn_no', 'm_system_code', ['code_kbn', 'code_no', 'factory_cd'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_kbn_no', 'm_system_code', type_='unique')
    op.create_unique_constraint('unique_kbn_no', 'm_system_code', ['code_kbn', 'code_no'])
    # ### end Alembic commands ###
