"""empty message

Revision ID: d658c1c69d81
Revises: b26b9b539e09
Create Date: 2021-08-29 00:03:14.012374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd658c1c69d81'
down_revision = 'b26b9b539e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('gender', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'gender')
    # ### end Alembic commands ###
